name: CI

on:
  push:
    branches:
      - riscv
  pull_request:
    branches:
      - riscv

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: svkv/riscv-tools:v1.0
    
    # Add fail-fast strategy
    strategy:
      fail-fast: true
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Clean build
      run: make clean
      # Add explicit failure condition
      if: success()

    - name: Build project
      run: |
        make
        # Check the make exit status
        if [ $? -ne 0 ]; then
          echo "Build failed"
          exit 1
        fi

    - name: Run QEMU tests
      run: |
        # Run QEMU with proper RISC-V options
        timeout 120 qemu-system-riscv64 \
          -machine virt \
          -nographic \
          -bios none \
          -kernel kernel/kernel \
          -m 128M \
          -smp 1 \
          > qemu_output.log 2>&1 &
        
        QEMU_PID=$!
        
        # Wait for QEMU to start
        sleep 30
        
        # Check QEMU status and output
        if ! kill -0 $QEMU_PID 2>/dev/null || grep -i "error\|failed" qemu_output.log; then
          echo "QEMU test failed"
          cat qemu_output.log
          exit 1
        fi
        
        # Kill QEMU process
        kill $QEMU_PID || true
